services: docker

jdk:
- openjdk8

git:
  submodules: false

before_install:
- git config --global url.https://$GITHUB_TOKEN@github.ibm.com/was-svt/sharedApps.insteadOf git@github.ibm.com:was-svt/sharedApps.git
- git submodule update --init --recursive
- docker login $CONT_REGISTRY -u $REG_USER -p $REG_PASSWORD
# - git clone git@github.ibm.com:was-svt/quicksec-jakarta.git

# - sudo apt-get -y install maven

script:
#- cd quicksec-jakarta/
- mvn clean package
- docker build -t quicksec-jakarta -f Containerfile --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD .
- tag=`git log --pretty=format:"%h" -1`
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:$tag
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:jdk8
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:latest
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:ga
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:$tag
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:latest
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:jdk
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:ga


- docker build -t quicksec-jakarta -f Containerfile --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD --build-arg FULL_IMAGE=true  --build-arg BASE_IMAGE="openliberty/daily:full-java8-openj9" .
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:daily
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:daily

- docker build -t quicksec-jakarta -f Containerfile --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD --build-arg FULL_IMAGE=true  --build-arg BASE_IMAGE="icr.io/appcafe/websphere-liberty:full-java8-openj9-ubi" .
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:wl-ga
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:wl-ga

- docker build -t quicksec-jakarta -f Containerfile --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD --build-arg FULL_IMAGE=true  --build-arg BASE_IMAGE="icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi" .
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:jdk8-java11
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:jdk8-java11

- docker build -t quicksec-jakarta -f Containerfile --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD --build-arg FULL_IMAGE=true  --build-arg BASE_IMAGE="icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi" .
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:jdk8-java17
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:jdk8-java17
