services: docker

jdk:
- openjdk8

before_install:
- sudo apt-get -y install git
- docker login $CONT_REGISTRY -u $REG_USER -p $REG_PASSWORD
- git clone git@github.ibm.com:was-svt/quicksec-jakarta.git

# - sudo apt-get -y install maven

script:
- cd quicksec-jakarta/
- mvn clean package
- docker build -t quicksec-jakarta --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD
- tag=`git log --pretty=format:"%h" -1`
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:$tag
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:latest
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:$tag
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:latest
