services: docker
dist: xenial

jdk:
- openjdk8

before_install:
- sudo apt-get -y install git
- docker login $artifactory -u $art_user -p $art_password
- git clone git@github.ibm.com:was-svt/quicksec-jakarta.git
- sudo apt-get -y install maven

script:
- cd quicksec-jakarta/
- mvn clean package
- docker build -t quicksec-jakarta .
- docker tag quicksec-jakarta $artifactory/quicksec/quicksec-jakarta:latest
- docker push  $artifactory/quicksec-jakarta:latest
