services: docker

jdk:
- openjdk8

before_install:
- sudo apt -y install python3 python3-pip
- sudo pip3 install setuptools
- sudo pip3 install --upgrade pip
- sudo pip3 install --upgrade setuptools

script:
# Install Ansible.
- pip3 install ansible

- |
  git clone https://$GITHUB_TOKEN@github.ibm.com/was-svt/configs.git --branch main -q
  echo "$pw" > /tmp/.pw
  configs/bin/decryptme.sh /tmp/.pw
  # env vars from the configs repo CONT_REGISTRY HYCSVT and the user / token
  . /tmp/.registry
  docker login $CONT_REGISTRY -u $(cat /tmp/.user) -p $(cat /tmp/.token)

- export DOCKER_BUILDKIT=1
- export BUILDKIT_PROGRESS=plain
- mvn -q clean package

# Pass variables from travis to create docker image from any base image and custom tag it 
- docker build -t quicksec-jakarta -f Containerfile --secret id=token,src=/tmp/.token --secret id=user,src=/tmp/.user --build-arg FULL_IMAGE=false  --build-arg BASE_IMAGE=$BASE_IMAGE .
- docker tag quicksec-jakarta $HYCSVT/quicksec/quicksec-jakarta:$IMAGE_TAG
- docker push  $HYCSVT/quicksec/quicksec-jakarta:$IMAGE_TAG


# Build and tag application based on WebnSphere Liberty with latest java versions
- docker build -t quicksec-jakarta -f Containerfile --secret id=token,src=/tmp/.token --secret id=user,src=/tmp/.user --build-arg FULL_IMAGE=true  --build-arg BASE_IMAGE="icr.io/appcafe/websphere-liberty:full-java17-openj9-ubi" .
- docker tag quicksec-jakarta $HYCSVT/quicksec/quicksec-jakarta:wl-jdk8-java17
- docker push  $HYCSVT/quicksec/quicksec-jakarta:wl-jdk8-java17

# Build and tag application based on Open Liberty with different java versions
- docker build -t quicksec-jakarta -f Containerfile --secret id=token,src=/tmp/.token --secret id=user,src=/tmp/.user --build-arg FULL_IMAGE=false  --build-arg BASE_IMAGE="icr.io/appcafe/open-liberty:kernel-slim-java8-openj9-ubi" .
- docker tag quicksec-jakarta $HYCSVT/quicksec/quicksec-jakarta:ol-jdk8-java8
- docker push  $HYCSVT/quicksec/quicksec-jakarta:ol-jdk8-java8

- docker build -t quicksec-jakarta -f Containerfile --secret id=token,src=/tmp/.token --secret id=user,src=/tmp/.user --build-arg FULL_IMAGE=false  --build-arg BASE_IMAGE="icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi" .
- docker tag quicksec-jakarta $HYCSVT/quicksec/quicksec-jakarta:ol-jdk8-java11
- docker push  $HYCSVT/quicksec/quicksec-jakarta:ol-jdk8-java11

- docker build -t quicksec-jakarta -f Containerfile --secret id=token,src=/tmp/.token --secret id=user,src=/tmp/.user --build-arg FULL_IMAGE=false  --build-arg BASE_IMAGE="icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi" .
- docker tag quicksec-jakarta $HYCSVT/quicksec/quicksec-jakarta:ol-jdk8-java17
- docker push  $HYCSVT/quicksec/quicksec-jakarta:ol-jdk8-java17
