services: docker
dist: xenial

jdk:
- openjdk8

before_install:
- sudo apt-get -y install git
- docker login $CONT_REGISTRY -u $REG_USER -p $REG_PASSWORD
- git clone git@github.ibm.com:was-svt/quicksec-jakarta.git
- tag=`git log --pretty=format:"%h" -1`
- sudo apt-get -y install maven

script:
- cd quicksec-jakarta/
- mvn clean package
- docker build -t quicksec-jakarta .
- docker tag quicksec-jakarta $CONT_REGISTRY/quicksec/quicksec-jakarta:$tag
- docker push  $CONT_REGISTRY/quicksec/quicksec-jakarta:$tag
