apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
    name: quicksec-jakarta
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    labels:
      app: quicksec_olo
spec:
  applicationImage: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/quicksec/quicksec-jakarta:latest
  statefulSet: {}
  createKnativeService: false
  expose: true
  serviceability:
    size: 2Gi  
  replicas: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  pullPolicy: Always
  service:
    type: ClusterIP
    port: 9443
  route:
    termination: passthrough
  resources:
    limits:
      cpu: 256m
      memory: 600Mi
    requests:
      cpu: 128m
      memory: 400Mi
  env:
    - name: DBHost
      value: 'qs-db2'
    - name: DBName
      value: MSGRDB
    - name: DBPort
      value: "50000"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      valueFrom:
        secretKeyRef:
          name: db-credential
          key: dbpw
