kind: Secret
apiVersion: v1
metadata:
  name: db-credential
  namespace: quicksec
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  dbpw: ZGIyaW5zdDEK
type: Opaque
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: quicksec
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quicksec
  - kind: ServiceAccount
    name: mysvcacct
    namespace: quicksec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: quicksec
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quicksec
  - kind: ServiceAccount
    name: mysvcacct
    namespace: quicksec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
subjects:
  - kind: ServiceAccount
    name: db2
    namespace: quicksec
  - kind: ServiceAccount
    name: default
    namespace: quicksec
  - kind: ServiceAccount
    name: quicksec
    namespace: quicksec
  - kind: ServiceAccount
    name: db2
    namespace: quicksec
  - kind: ServiceAccount
    name: default
    namespace: quicksec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: quicksec
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quicksec
  - kind: ServiceAccount
    name: mysvcacct
    namespace: quicksec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
