apiVersion: batch/v1
kind: Job
metadata:
  name: quicksec-jmeter-config
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          env:
            - name: ARGOCD_APP_NAMESPACE
              value: $ARGOCD_APP_NAMESPACE
            - name: ARGOCD_APP_NAME
              value: $ARGOCD_APP_NAME
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x
              result=0
              route=$(oc get route quicksec-jakarta -o jsonpath='{.spec.host}')
              oc delete configmap jmeter-route
              oc create configmap jmeter-route --from-literal=app-route=$route
      restartPolicy: Never
      serviceAccountName:  runneracct
