apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
    name: quicksec-jakarta
    namespace: quicksec
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
    metric: Virtual Processor Core (VPC)
  applicationImage: hyc-wassvt-team-image-registry-docker-local.artifactory.swg-devops.com/quicksec/quicksec-jakarta:latest
  statefulSet: {}
  createKnativeService: false
  expose: true
  serviceability:
    size: 2Gi  
  replicas: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  pullPolicy: Always
  service:
    type: ClusterIP
    port: 9443
  route:
    termination: passthrough
  resources:
    limits:
      cpu: 256m
      memory: 600Mi
    requests:
      cpu: 128m
      memory: 400Mi
  probes:
    readiness:
      failureThreshold: 12
      httpGet:
        path: /health/ready
        port: 9080
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      failureThreshold: 12
      httpGet:
        path: /health/live
        port: 9080
      initialDelaySeconds: 15
      periodSeconds: 20
  env:
    - name: DBHost
      value: 'qs-db2.quicksec'
    - name: DBName
      value: MSGRDB
    - name: DBPort
      value: "50000"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      value: db2passwd
