apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
    name: quicksec-jakarta
    namespace: quicksec
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  applicationImage: hyc-wassvt-team-image-registry-docker-local.artifactory.swg-devops.com/quicksec/quicksec-jakarta:latest 
  createKnativeService: false
  expose: true
  replicas: 1
  pullPolicy: Always
  pullSecret: pull-secret
  service:
    type: ClusterIP
    port: 9443
    annotations:
      prometheus.io/scrape: 'true'
  route:
    termination: passthrough  
  resources:
    limits:
      cpu: 256m
      memory: 400Mi
    requests:
      cpu: 256m
  env:
    - name: DBHost
      value: 'qs-db2.quicksec'
    - name: DBName
      value: MSGRDB
    - name: DBPort
      value: "50000"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      value: db2passwd
