apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-reader
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-logs
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
- kind: ServiceAccount
  name: gather-rb
  apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gather-rb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: openshift-config
  name: list-secrets-role
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "delete", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: list-secrets-role-binding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
- kind: ServiceAccount
  name: gather-rb
  namespace: quicksec-wlo
  apiGroup: ""
roleRef:
  kind: Role
  name: list-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: gather-scc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
allowPrivilegedContainer: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowHostDirVolumePlugin: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
groups:
- system:serviceaccounts
