---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gather-rb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gather-admin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: gather-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: gather-scc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
allowPrivilegedContainer: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowHostDirVolumePlugin: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
groups:
- system:serviceaccounts
