apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
      deployment: openldap
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openldap
        deployment: openldap
    spec:
      containers:
        - resources: {}
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: LDAP_ENABLE_TLS
              value: 'yes'
          terminationMessagePath: /dev/termination-log
          name: openldap
          #command: ['bash','-c','./svt-ldapadd.sh']
          securityContext:
            capabilities:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 9389
              protocol: TCP
            - containerPort: 9636
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/svt-openldap/svt-openldap
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
---

kind: Service
apiVersion: v1
metadata:
  name: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: openldap
spec:
  ports:
    - name: 9389-tcp
      protocol: TCP
      port: 9389
      targetPort: 9389
    - name: 9636-tcp
      protocol: TCP
      port: 9636
      targetPort: 9636
  selector:
    app: openldap
    deployment: openldap
  type: ClusterIP
  sessionAffinity: None
